name: code

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 20 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.rust-toolchain.name }} / ${{ matrix.platform.name }} / ${{ matrix.mode.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        rust-toolchain:
          - name: stable
            allow-fail: false

        platform:
          - name: Linux
            os: ubuntu-latest
            env: {}
            experimental: false

        mode:
          - name: clippy
            cargo-command: clippy
            cargo-args: --workspace -- -D warnings
          - name: test
            cargo-command: test
            cargo-args: --workspace
          - name: build
            cargo-command: build
            cargo-args: --workspace

      fail-fast: false
    continue-on-error: ${{ matrix.platform.experimental || matrix.rust-toolchain.allow-fail }}
    env: ${{ matrix.platform.env }}
    steps:
      - name: Job config
        run: echo "$MATRIX_CONTEXT"
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain.name }}
          components: rustfmt, clippy
          default: true

      - name: Set up Vistual Studio Command Prompt (Windows only)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Print build environment info
        run: |
          set -x
          cargo --version
          cargo clippy --version
          env

      - name: Run cargo ${{ matrix.mode.cargo-command }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.mode.cargo-command }}
          args: ${{ matrix.mode.cargo-args }}
